appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jcRk/FpIaY54ZeqzMnnpFFFcsaIZryOZuEY32HaoSfP7lItqOxEY/sH9naJj5sJdUfMEuuhSU85XqAQCFbraMXUBSy44t6cqDlIQBrGEARbkfVt7MnBNPuIwn04Pm9PeOgj2s2ZxdTYy8Mea/R56U6Dx4h2qyosQIUoPZHpmcvN2jcAiYk7oT40a7AAtAkqCa1U5okFeGUJyyWsflRHetPP6Ioy4uSOjjYPoIVKZ1hwjLj8ZALXbECdTXeuQqXgJUOAie0dMcqXRgzvRoRLgp+hz8hwFAV/jZILu1nhDXBOYM3NOgLzLYV6Iie6UzRxlzopGPEm2mqL6zeE/5mTTwhOapQAbzyY9iQG5YYN3xGF4237H+jIifGhxiBsNTxX7eYkeyWrUmbIAVl9VeDNkSh9VQLlfI919a7B5h6kIR/b6vGYFefl7hQuyfvZessdNBh2oJCYLuEWnqwKLRt+swX4e3JCxLABfOcMn+YqeqHwfv5MQ7l/jP06L32YcI4NI4x+VWCjm4iIo5GWnCIi1+2s4o6TguhZg5ziEZKqNjrK1Q4eanXj5+1KcN0J8cnuN90xvciED37OehaTs/25z/K1JOBjguXeEvsUVuavEaPID9FhlmuUAghGMy4pkvt77VsrtT7+WXSHFAznNrmOb2vlrdzAp5+jUuauhTjmkD5k=}
